# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos9611-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a51 m31 m21 f41 m31s,$(TARGET_DEVICE)),)

endif
